### ISSUE TITLE
Documentation doesn’t show how to connect the pieces

### ISSUE THREAD

**Issue by leafac** [nanopass/nanopass-framework-racket#15] opened 2017-02-14 13:08 UTC
The documentation shows how to define languages and passes. But doesn’t show how put them together to form a compiler. In particular, it has no example of using the parser, nor does it explain `with-output-language`.

In my exploration of the source, I figure the following works:

```racket
(make-explicit (with-output-language (L0 Expr) `(if 0 1)))
;; => (language:L1 '(if '0 '1 (void)))

(define-parser parse-L0 L0)
(make-explicit (parse-L0 '(if 0 1)))
;; => (language:L1 '(if '0 '1 (void)))
```

But it’s not included in the documentation, and I’m not sure which option is right and what are the implications.

Also, it’d be nice to have documentation for the tracing feature shown in this talk: https://www.youtube.com/watch?v=Os7FE3J-U5Q

**Comment by dented42** [comment] 2017-10-25 20:55
This almost kinda seems like a duplicate of issue #1?

**Comment by leafac** [comment] 2017-10-27 17:08
I guess you’re right. By the way, the tutorial mentioned there [is here](https://github.com/LeifAndersen/nanopasstutorial). It isn’t finished yet, but it helped me anyway.

**Closed as completed** 2019-07-17 16:29 UTC
